# Generated by Django 4.1.1 on 2022-12-15 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MotifForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgBefore', models.TextField(max_length=50)),
                ('imgAfter', models.TextField(max_length=50)),
                ('urutanLidi', models.TextField(max_length=100)),
            ],
            options={
                'db_table': 'Motif',
            },
        ),
    ]
