# Generated by Django 4.1.1 on 2022-12-15 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motifform',
            name='imgAfter',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='motifform',
            name='imgBefore',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='motifform',
            name='urutanLidi',
            field=models.TextField(),
        ),
    ]
