# Generated by Django 4.1.1 on 2022-12-15 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0005_alter_motifform_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='motifform',
            table=None,
        ),
    ]
