# Generated by Django 4.1.1 on 2023-02-14 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0006_alter_motifform_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotifForm1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgBefore', models.TextField()),
                ('imgAfter', models.TextField()),
                ('urutanLidi', models.TextField()),
                ('jenisGenerate', models.TextField()),
                ('jmlBaris', models.TextField()),
                ('jmlLidi', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
