# Generated by Django 4.1.1 on 2023-02-14 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0007_motifform1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='motifform1',
            old_name='jmlLidi',
            new_name='user',
        ),
    ]
