# Generated by Django 4.1.1 on 2025-02-12 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0008_rename_jmllidi_motifform1_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Motif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='motifs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
