# Generated by Django 4.1.1 on 2025-02-12 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0009_motif'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Motif',
        ),
    ]
