# Generated by Django 4.1.1 on 2025-06-20 03:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0011_motif'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motif',
            name='description',
        ),
        migrations.RemoveField(
            model_name='motif',
            name='name',
        ),
        migrations.AddField(
            model_name='motif',
            name='Urutan',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='motif',
            name='edit_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='motif',
            name='jenis',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='motif',
            name='jmlBaris',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='motif',
            name='raw_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='motif',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='motif',
            name='user',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='motifform1',
            name='coloredImage',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='motifform1',
            name='coloredImagecombined',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='motifform1',
            name='slice',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='motifform1',
            name='sliceColoredImage',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='motifform1',
            name='urutanLidiAsal',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='motifform1',
            table='website_motifform1',
        ),
    ]
