# Generated by Django 4.1.1 on 2025-06-20 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0012_remove_motif_description_remove_motif_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='motifform1',
            name='jenisKain',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='motifform1',
            name='jenisProduk',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='motifform1',
            name='coloredImage',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='motifform1',
            name='coloredImagecombined',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='motifform1',
            name='imgAfter',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='motifform1',
            name='imgBefore',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='motifform1',
            name='jenisGenerate',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='motifform1',
            name='jmlBaris',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='motifform1',
            name='slice',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='motifform1',
            name='sliceColoredImage',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='motifform1',
            name='urutanLidi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='motifform1',
            name='user',
            field=models.TextField(blank=True, null=True),
        ),
    ]
