# Generated by Django 4.1.1 on 2025-06-20 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0013_alter_motifform1_coloredimage_and_more'),
        ('Website', '0013_motifform1_jeniskain_motifform1_jenisproduk_and_more'),
    ]

    operations = [
    ]
