# Generated by Django 4.1.1 on 2025-06-26 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0014_merge_20250620_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='motif',
            name='lebar',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='motif',
            name='panjang',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='motifform1',
            name='lebar',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='motifform1',
            name='panjang',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
