# Generated by Django 4.1.1 on 2025-08-25 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0015_motif_lebar_motif_panjang_motifform1_lebar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UlosCharacteristic',
            fields=[
                ('NAME', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('garis', models.TextField()),
                ('pola', models.TextField()),
                ('warna_dominasi', models.TextField()),
                ('warna_aksen', models.TextField()),
                ('kontras_warna', models.TextField()),
            ],
            options={
                'verbose_name': 'Ulos Characteristic',
                'verbose_name_plural': 'Ulos Characteristics',
                'db_table': 'ulos_characteristic',
            },
        ),
        migrations.CreateModel(
            name='UlosColorThread',
            fields=[
                ('CODE', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('hsv', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Ulos Color Thread',
                'verbose_name_plural': 'Ulos Color Threads',
                'db_table': 'ulos_color_thread',
            },
        ),
        migrations.RemoveField(
            model_name='motif',
            name='lebar',
        ),
        migrations.RemoveField(
            model_name='motif',
            name='panjang',
        ),
        migrations.RemoveField(
            model_name='motifform1',
            name='lebar',
        ),
        migrations.RemoveField(
            model_name='motifform1',
            name='panjang',
        ),
    ]
